# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ml_pb2 as ml__pb2


class MlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPredictions = channel.unary_unary(
                '/ml.Ml/GetPredictions',
                request_serializer=ml__pb2.BookingPredictRequest.SerializeToString,
                response_deserializer=ml__pb2.IsCanceledResultResponse.FromString,
                )
        self.TrainModel = channel.unary_unary(
                '/ml.Ml/TrainModel',
                request_serializer=ml__pb2.BookingTrainRequest.SerializeToString,
                response_deserializer=ml__pb2.IsTrained.FromString,
                )


class MlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPredictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=ml__pb2.BookingPredictRequest.FromString,
                    response_serializer=ml__pb2.IsCanceledResultResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=ml__pb2.BookingTrainRequest.FromString,
                    response_serializer=ml__pb2.IsTrained.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.Ml', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ml(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.Ml/GetPredictions',
            ml__pb2.BookingPredictRequest.SerializeToString,
            ml__pb2.IsCanceledResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.Ml/TrainModel',
            ml__pb2.BookingTrainRequest.SerializeToString,
            ml__pb2.IsTrained.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
