// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ml.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MlClient is the client API for Ml service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlClient interface {
	GetPredictions(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*IsCanceledResultResponse, error)
}

type mlClient struct {
	cc grpc.ClientConnInterface
}

func NewMlClient(cc grpc.ClientConnInterface) MlClient {
	return &mlClient{cc}
}

func (c *mlClient) GetPredictions(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*IsCanceledResultResponse, error) {
	out := new(IsCanceledResultResponse)
	err := c.cc.Invoke(ctx, "/ml.Ml/GetPredictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlServer is the server API for Ml service.
// All implementations must embed UnimplementedMlServer
// for forward compatibility
type MlServer interface {
	GetPredictions(context.Context, *BookingRequest) (*IsCanceledResultResponse, error)
	mustEmbedUnimplementedMlServer()
}

// UnimplementedMlServer must be embedded to have forward compatible implementations.
type UnimplementedMlServer struct {
}

func (UnimplementedMlServer) GetPredictions(context.Context, *BookingRequest) (*IsCanceledResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredictions not implemented")
}
func (UnimplementedMlServer) mustEmbedUnimplementedMlServer() {}

// UnsafeMlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlServer will
// result in compilation errors.
type UnsafeMlServer interface {
	mustEmbedUnimplementedMlServer()
}

func RegisterMlServer(s grpc.ServiceRegistrar, srv MlServer) {
	s.RegisterService(&Ml_ServiceDesc, srv)
}

func _Ml_GetPredictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlServer).GetPredictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ml.Ml/GetPredictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlServer).GetPredictions(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ml_ServiceDesc is the grpc.ServiceDesc for Ml service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ml_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.Ml",
	HandlerType: (*MlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPredictions",
			Handler:    _Ml_GetPredictions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml.proto",
}
